apiVersion: v1
kind: Service
metadata:
  name: car-rental-service
spec:
  type: NodePort
  selector:
    app: car-rental
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007